version: "2.1.1"
services:
  db:
      image: mysql:5.7
      ports:
          - "3307:3306"
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
