version: "3"
services:
  db:
    image: mysql:5.7
    ports:
        - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - .:/demo_app_docker
    environment:
      # MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
  app:
    build: .
    command: bundle exec rails s -p 3000 -b "0.0.0.0"
    env_file:
      - .env
    volumes:
      - .:/demo_app_docker
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
volumes:
  db_data:
