default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: db
development:
  <<: *default
  database: db_docker_development

test:
  <<: *default
  database: rails_docker_test

production:
  <<: *default
  database: rails_docker_production
  username: rails_docker
  password: <%= ENV["DB_DOCKER_DATABASE_PASSWORD"] %>
