default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: abc
  host: <%= ENV["DATABASE_HOST"] %>
  socket: /tmp/mysql.sock
development:
  <<: *default
  database: db_docker_demo_development

test:
  <<: *default
  database: db_docker_demo_test

production:
  <<: *default
  database: db_docker_demo_production
  username: db_docker_demo
  password: <%= ENV["DB_DOCKER_DEMO_DATABASE_PASSWORD"] %>
